name: Run unit tests and publish samples

on:  #Name of the GitHub event that triggers the workflow
  push:   #On Push Event We need to take action
    branches:  #Now we need to specify the branch name
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - name: npm install 
      run: npm install
    - name: build 
      run: |
        npx vue-cli-service build
    - name: Configure AWS Credentials  
      uses: aws-actions/configure-aws-credentials@v1 #--> Setup the Credential for the AWS cli
      with:
      # Created the Secrets Under the Repo only with These Variables
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 #--> Define Region of the AWS-CLI 
    - name: deploy
      run: |  
        aws s3 sync ./dist s3://test-23423434 --delete
